ALTER TABLE projets CHANGE description description LONGTEXT DEFAULT NULL, CHANGE objectifs objectifs LONGTEXT DEFAULT NULL, CHANGE etat etat VARCHAR(255) DEFAULT 'En attente' NOT NULL, CHANGE commentaire_admin commentaire_admin LONGTEXT DEFAULT NULL, CHANGE date_soumission date_soumission DATETIME DEFAULT NULL, CHANGE note_moyenne note_moyenne DOUBLE PRECISION DEFAULT NULL, CHANGE evaluation_automatique evaluation_automatique TINYINT DEFAULT NULL, CHANGE ai_score_global ai_score_global NUMERIC(5, 2) DEFAULT NULL, CHANGE ai_analysis_data ai_analysis_data LONGTEXT DEFAULT NULL, CHANGE market_score market_score NUMERIC(5, 2) DEFAULT NULL, CHANGE market_data market_data LONGTEXT DEFAULT NULL, CHANGE patent_novelty_score patent_novelty_score NUMERIC(5, 2) DEFAULT NULL, CHANGE patent_data patent_data LONGTEXT DEFAULT NULL, CHANGE experiences_anterieures experiences_anterieures LONGTEXT DEFAULT NULL, CHANGE partenaires_potentiels partenaires_potentiels LONGTEXT DEFAULT NULL;
ALTER TABLE projets ADD CONSTRAINT FK_B454C1DBD14DE5D1 FOREIGN KEY (id_entrepreneur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
DROP INDEX id_entrepreneur ON projets;
CREATE INDEX IDX_B454C1DBD14DE5D1 ON projets (id_entrepreneur);
ALTER TABLE taches DROP FOREIGN KEY `taches_ibfk_1`;
ALTER TABLE taches DROP FOREIGN KEY `taches_ibfk_2`;
ALTER TABLE taches DROP FOREIGN KEY `taches_ibfk_3`;
ALTER TABLE taches DROP FOREIGN KEY `taches_ibfk_1`;
ALTER TABLE taches DROP FOREIGN KEY `taches_ibfk_2`;
ALTER TABLE taches DROP FOREIGN KEY `taches_ibfk_3`;
ALTER TABLE taches CHANGE description description LONGTEXT DEFAULT NULL, CHANGE statut statut VARCHAR(255) DEFAULT '├Ç faire' NOT NULL;
ALTER TABLE taches ADD CONSTRAINT FK_3BF2CD9876222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE;
ALTER TABLE taches ADD CONSTRAINT FK_3BF2CD98C9B7E05A FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE CASCADE;
ALTER TABLE taches ADD CONSTRAINT FK_3BF2CD984A40C0F0 FOREIGN KEY (id_responsable) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
DROP INDEX id_projet ON taches;
CREATE INDEX IDX_3BF2CD9876222944 ON taches (id_projet);
DROP INDEX id_sprint ON taches;
CREATE INDEX IDX_3BF2CD98C9B7E05A ON taches (id_sprint);
DROP INDEX id_responsable ON taches;
CREATE INDEX IDX_3BF2CD984A40C0F0 ON taches (id_responsable);
ALTER TABLE taches ADD CONSTRAINT `taches_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet);
ALTER TABLE taches ADD CONSTRAINT `taches_ibfk_2` FOREIGN KEY (id_responsable) REFERENCES utilisateurs (id_utilisateur);
ALTER TABLE taches ADD CONSTRAINT `taches_ibfk_3` FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE SET NULL;
ALTER TABLE membres_equipe DROP FOREIGN KEY `membres_equipe_ibfk_1`;
ALTER TABLE membres_equipe DROP FOREIGN KEY `membres_equipe_ibfk_2`;
ALTER TABLE membres_equipe DROP FOREIGN KEY `membres_equipe_ibfk_1`;
ALTER TABLE membres_equipe DROP FOREIGN KEY `membres_equipe_ibfk_2`;
ALTER TABLE membres_equipe ADD CONSTRAINT FK_C184283276222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE;
ALTER TABLE membres_equipe ADD CONSTRAINT FK_C184283250EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
DROP INDEX id_projet ON membres_equipe;
CREATE INDEX IDX_C184283276222944 ON membres_equipe (id_projet);
DROP INDEX id_utilisateur ON membres_equipe;
CREATE INDEX IDX_C184283250EAE44 ON membres_equipe (id_utilisateur);
ALTER TABLE membres_equipe ADD CONSTRAINT `membres_equipe_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet);
ALTER TABLE membres_equipe ADD CONSTRAINT `membres_equipe_ibfk_2` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur);
ALTER TABLE ressources DROP FOREIGN KEY `ressources_ibfk_1`;
ALTER TABLE ressources DROP FOREIGN KEY `ressources_ibfk_1`;
ALTER TABLE ressources CHANGE nom nom VARCHAR(150) NOT NULL, CHANGE offre offre VARCHAR(30) NOT NULL, CHANGE type_r type_r VARCHAR(30) NOT NULL, CHANGE image_r image_r VARCHAR(255) NOT NULL, CHANGE prix_achat prix_achat DOUBLE PRECISION NOT NULL, CHANGE disponibilite disponibilite TINYINT NOT NULL, CHANGE prix_louer prix_louer DOUBLE PRECISION NOT NULL, CHANGE unite_louer unite_louer VARCHAR(30) NOT NULL, CHANGE quantite quantite INT NOT NULL, CHANGE etat etat VARCHAR(30) NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE is_banned is_banned TINYINT NOT NULL, CHANGE moderation_score moderation_score INT NOT NULL;
ALTER TABLE ressources ADD CONSTRAINT FK_6A2CD5C72E8C07C5 FOREIGN KEY (id_fournisseur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
DROP INDEX id_fournisseur ON ressources;
CREATE INDEX IDX_6A2CD5C72E8C07C5 ON ressources (id_fournisseur);
ALTER TABLE ressources ADD CONSTRAINT `ressources_ibfk_1` FOREIGN KEY (id_fournisseur) REFERENCES utilisateurs (id_utilisateur);
ALTER TABLE resource_reports DROP FOREIGN KEY `FK_F80875C950EAE40`;
ALTER TABLE resource_reports DROP FOREIGN KEY `FK_F80875C965D678E1`;
ALTER TABLE utilisateurs DROP FOREIGN KEY `utilisateurs_ibfk_1`;
ALTER TABLE utilisateurs CHANGE nom nom VARCHAR(100) NOT NULL, CHANGE bio bio LONGTEXT DEFAULT NULL, CHANGE competences competences LONGTEXT DEFAULT NULL, CHANGE date_inscription date_inscription DATETIME NOT NULL, CHANGE badge_verifie badge_verifie TINYINT DEFAULT 0 NOT NULL, CHANGE profil_complet profil_complet TINYINT DEFAULT 0 NOT NULL, CHANGE actif actif TINYINT DEFAULT 1 NOT NULL, CHANGE adresse adresse VARCHAR(255) DEFAULT NULL, CHANGE latitude latitude DOUBLE PRECISION DEFAULT NULL, CHANGE longitude longitude DOUBLE PRECISION DEFAULT NULL, CHANGE avatar_url avatar_url VARCHAR(255) DEFAULT NULL;
DROP INDEX email ON utilisateurs;
CREATE UNIQUE INDEX UNIQ_497B315EE7927C74 ON utilisateurs (email);
DROP INDEX id_role ON utilisateurs;
CREATE INDEX IDX_497B315EDC499668 ON utilisateurs (id_role);
ALTER TABLE utilisateurs ADD CONSTRAINT `utilisateurs_ibfk_1` FOREIGN KEY (id_role) REFERENCES roles (id_role);
ALTER TABLE lignes_commande CHANGE id_commande id_commande INT DEFAULT NULL, CHANGE id_ressource id_ressource INT DEFAULT NULL, CHANGE quantite quantite INT NOT NULL, CHANGE date_deb date_deb DATE NOT NULL, CHANGE date_fin date_fin DATE NOT NULL, CHANGE prix_ligne prix_ligne VARCHAR(255) NOT NULL;
ALTER TABLE lignes_commande ADD CONSTRAINT FK_DAAE0FCB3E314AE8 FOREIGN KEY (id_commande) REFERENCES commandes (id_commande) ON DELETE CASCADE;
ALTER TABLE lignes_commande ADD CONSTRAINT FK_DAAE0FCB13AAF963 FOREIGN KEY (id_ressource) REFERENCES ressources (id_ressource) ON DELETE CASCADE;
DROP INDEX id_commande ON lignes_commande;
CREATE INDEX IDX_DAAE0FCB3E314AE8 ON lignes_commande (id_commande);
DROP INDEX id_ressource ON lignes_commande;
CREATE INDEX IDX_DAAE0FCB13AAF963 ON lignes_commande (id_ressource);
ALTER TABLE demandes_ressources DROP FOREIGN KEY `FK_B57BECB213AAF963`;
ALTER TABLE demandes_ressources DROP FOREIGN KEY `FK_B57BECB2D14DE5D1`;
DROP INDEX id_ressource ON demandes_ressources;
CREATE INDEX IDX_B57BECB213AAF963 ON demandes_ressources (id_ressource);
DROP INDEX id_entrepreneur ON demandes_ressources;
CREATE INDEX IDX_B57BECB2D14DE5D1 ON demandes_ressources (id_entrepreneur);
ALTER TABLE demandes_ressources ADD CONSTRAINT `FK_B57BECB213AAF963` FOREIGN KEY (id_ressource) REFERENCES ressources (id_ressource) ON DELETE CASCADE;
ALTER TABLE demandes_ressources ADD CONSTRAINT `FK_B57BECB2D14DE5D1` FOREIGN KEY (id_entrepreneur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
DROP INDEX idx_date ON demandes_verification;
DROP INDEX idx_statut ON demandes_verification;
ALTER TABLE demandes_verification CHANGE id_utilisateur id_utilisateur INT DEFAULT NULL, CHANGE type_role type_role VARCHAR(50) NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE raison_demande raison_demande LONGTEXT NOT NULL, CHANGE document_justificatif document_justificatif VARCHAR(255) NOT NULL, CHANGE date_demande date_demande DATETIME NOT NULL, CHANGE date_traitement date_traitement DATETIME NOT NULL, CHANGE commentaire_admin commentaire_admin LONGTEXT NOT NULL;
ALTER TABLE demandes_verification ADD CONSTRAINT FK_57BC1FE750EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
ALTER TABLE demandes_verification ADD CONSTRAINT FK_57BC1FE7C9DD9712 FOREIGN KEY (id_admin_traitant) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
DROP INDEX idx_utilisateur ON demandes_verification;
CREATE INDEX IDX_57BC1FE750EAE44 ON demandes_verification (id_utilisateur);
DROP INDEX id_admin_traitant ON demandes_verification;
CREATE INDEX IDX_57BC1FE7C9DD9712 ON demandes_verification (id_admin_traitant);
ALTER TABLE demande_emplois CHANGE cv_url cv_url VARCHAR(255) DEFAULT NULL, CHANGE lettre_motivation lettre_motivation LONGTEXT DEFAULT NULL, CHANGE motivation_ciblee motivation_ciblee LONGTEXT DEFAULT NULL, CHANGE statut_demande statut_demande VARCHAR(50) NOT NULL;
ALTER TABLE evaluations_projet DROP FOREIGN KEY `evaluations_projet_ibfk_1`;
ALTER TABLE evaluations_projet DROP FOREIGN KEY `evaluations_projet_ibfk_2`;
ALTER TABLE evaluations_projet DROP FOREIGN KEY `evaluations_projet_ibfk_1`;
ALTER TABLE evaluations_projet DROP FOREIGN KEY `evaluations_projet_ibfk_2`;
ALTER TABLE evaluations_projet CHANGE note_originalite note_originalite INT NOT NULL, CHANGE note_faisabilite note_faisabilite INT NOT NULL, CHANGE note_impact note_impact INT NOT NULL, CHANGE note_clarte note_clarte INT NOT NULL, CHANGE note_budget note_budget INT NOT NULL, CHANGE commentaire commentaire LONGTEXT NOT NULL, CHANGE date_evaluation date_evaluation DATETIME NOT NULL;
ALTER TABLE evaluations_projet ADD CONSTRAINT FK_24EC14B976222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE;
ALTER TABLE evaluations_projet ADD CONSTRAINT FK_24EC14B9668B4C46 FOREIGN KEY (id_admin) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
DROP INDEX id_projet ON evaluations_projet;
CREATE INDEX IDX_24EC14B976222944 ON evaluations_projet (id_projet);
DROP INDEX id_admin ON evaluations_projet;
CREATE INDEX IDX_24EC14B9668B4C46 ON evaluations_projet (id_admin);
ALTER TABLE evaluations_projet ADD CONSTRAINT `evaluations_projet_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet);
ALTER TABLE evaluations_projet ADD CONSTRAINT `evaluations_projet_ibfk_2` FOREIGN KEY (id_admin) REFERENCES utilisateurs (id_utilisateur);
ALTER TABLE evenements CHANGE titre titre VARCHAR(150) NOT NULL, CHANGE lieu lieu VARCHAR(150) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE prix prix DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE fichiers_projet DROP FOREIGN KEY `fk_fichier_projet`;
ALTER TABLE fichiers_projet DROP FOREIGN KEY `fk_fichier_user`;
DROP INDEX idx_fichier_projet ON fichiers_projet;
CREATE INDEX IDX_DC6CF00476222944 ON fichiers_projet (id_projet);
DROP INDEX idx_fichier_user ON fichiers_projet;
CREATE INDEX IDX_DC6CF004FBF5FCD1 ON fichiers_projet (id_uploaded_by);
ALTER TABLE fichiers_projet ADD CONSTRAINT `fk_fichier_projet` FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE;
ALTER TABLE fichiers_projet ADD CONSTRAINT `fk_fichier_user` FOREIGN KEY (id_uploaded_by) REFERENCES utilisateurs (id_utilisateur);
DROP INDEX idx_adresse_ip ON historique_connexions;
DROP INDEX idx_date_connexion ON historique_connexions;
ALTER TABLE historique_connexions DROP FOREIGN KEY `historique_connexions_ibfk_1`;
ALTER TABLE historique_connexions CHANGE id_utilisateur id_utilisateur INT DEFAULT NULL, CHANGE ville ville VARCHAR(100) NOT NULL, CHANGE pays pays VARCHAR(100) NOT NULL, CHANGE region region VARCHAR(100) NOT NULL, CHANGE code_postal code_postal VARCHAR(20) NOT NULL, CHANGE timezone timezone VARCHAR(50) NOT NULL, CHANGE date_connexion date_connexion DATETIME NOT NULL, CHANGE user_agent user_agent LONGTEXT NOT NULL;
DROP INDEX idx_utilisateur ON historique_connexions;
CREATE INDEX IDX_9A70C17450EAE44 ON historique_connexions (id_utilisateur);
ALTER TABLE historique_connexions ADD CONSTRAINT `historique_connexions_ibfk_1` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
DROP INDEX idx_messages_conversation ON messages;
ALTER TABLE messages DROP FOREIGN KEY `messages_ibfk_2`;
ALTER TABLE messages CHANGE contenu contenu LONGTEXT NOT NULL, CHANGE date_envoi date_envoi DATETIME NOT NULL, CHANGE est_lu est_lu TINYINT NOT NULL, CHANGE est_modifie est_modifie TINYINT NOT NULL, CHANGE est_supprime est_supprime TINYINT NOT NULL, CHANGE type_contenu type_contenu VARCHAR(255) NOT NULL, CHANGE piece_jointe piece_jointe VARCHAR(255) NOT NULL;
DROP INDEX id_expediteur ON messages;
CREATE INDEX IDX_DB021E96E2E4F59 ON messages (id_expediteur);
ALTER TABLE messages ADD CONSTRAINT `messages_ibfk_2` FOREIGN KEY (id_expediteur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D350EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
CREATE INDEX IDX_6000B0D350EAE44 ON notifications (id_utilisateur);
ALTER TABLE otp_codes CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE attempts attempts INT DEFAULT 0 NOT NULL, CHANGE used used TINYINT DEFAULT 0 NOT NULL, ADD PRIMARY KEY (id);
DROP INDEX idx_token ON password_reset_tokens;
DROP INDEX idx_expiration ON password_reset_tokens;
DROP INDEX token ON password_reset_tokens;
ALTER TABLE password_reset_tokens DROP FOREIGN KEY `password_reset_tokens_ibfk_1`;
ALTER TABLE password_reset_tokens CHANGE id_utilisateur id_utilisateur INT DEFAULT NULL, CHANGE date_creation date_creation DATETIME NOT NULL, CHANGE date_expiration date_expiration DATETIME NOT NULL, CHANGE utilise utilise TINYINT NOT NULL;
DROP INDEX id_utilisateur ON password_reset_tokens;
CREATE INDEX IDX_3967A21650EAE44 ON password_reset_tokens (id_utilisateur);
ALTER TABLE password_reset_tokens ADD CONSTRAINT `password_reset_tokens_ibfk_1` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
ALTER TABLE reclamations DROP FOREIGN KEY `reclamations_ibfk_1`;
ALTER TABLE reclamations DROP adresse, DROP latitude, DROP longitude, DROP emotion, DROP reponse_admin, DROP date_modification, DROP date_resolution, DROP commentaire_admin, DROP updated_at, DROP image_path, CHANGE id_utilisateur id_utilisateur INT NOT NULL, CHANGE sujet sujet VARCHAR(150) NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE statut statut VARCHAR(20) NOT NULL, CHANGE date_creation date_creation DATETIME NOT NULL;
DROP INDEX id_utilisateur ON reclamations;
CREATE INDEX IDX_1CAD6B7650EAE44 ON reclamations (id_utilisateur);
ALTER TABLE reclamations ADD CONSTRAINT `reclamations_ibfk_1` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur);
ALTER TABLE reclamation_commentaires DROP FOREIGN KEY `fk_commentaire_auteur`;
ALTER TABLE reclamation_commentaires DROP FOREIGN KEY `reclamation_commentaires_ibfk_1`;
ALTER TABLE reclamation_commentaires CHANGE id_reclamation id_reclamation INT DEFAULT NULL, CHANGE id_auteur id_auteur INT DEFAULT NULL, CHANGE commentaire commentaire LONGTEXT NOT NULL, CHANGE date_commentaire date_commentaire DATETIME NOT NULL;
DROP INDEX id_reclamation ON reclamation_commentaires;
CREATE INDEX IDX_5EAA37A6D672A9F3 ON reclamation_commentaires (id_reclamation);
DROP INDEX fk_commentaire_auteur ON reclamation_commentaires;
CREATE INDEX IDX_5EAA37A6236D04AD ON reclamation_commentaires (id_auteur);
ALTER TABLE reclamation_commentaires ADD CONSTRAINT `fk_commentaire_auteur` FOREIGN KEY (id_auteur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
ALTER TABLE reclamation_commentaires ADD CONSTRAINT `reclamation_commentaires_ibfk_1` FOREIGN KEY (id_reclamation) REFERENCES reclamations (id_reclamation) ON DELETE CASCADE;
ALTER TABLE reservations DROP FOREIGN KEY `reservations_ibfk_1`;
ALTER TABLE reservations DROP FOREIGN KEY `reservations_ibfk_2`;
ALTER TABLE reservations DROP FOREIGN KEY `reservations_ibfk_1`;
ALTER TABLE reservations DROP FOREIGN KEY `reservations_ibfk_2`;
ALTER TABLE reservations DROP verified_at, DROP payment_status, CHANGE date_reservation date_reservation DATETIME NOT NULL;
ALTER TABLE reservations ADD CONSTRAINT FK_4DA2398B13D439 FOREIGN KEY (id_evenement) REFERENCES evenements (id_evenement) ON DELETE CASCADE;
ALTER TABLE reservations ADD CONSTRAINT FK_4DA23950EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE;
DROP INDEX token_verification ON reservations;
CREATE UNIQUE INDEX UNIQ_4DA2394A078E03 ON reservations (token_verification);
DROP INDEX id_evenement ON reservations;
CREATE INDEX IDX_4DA2398B13D439 ON reservations (id_evenement);
DROP INDEX id_utilisateur ON reservations;
CREATE INDEX IDX_4DA23950EAE44 ON reservations (id_utilisateur);
ALTER TABLE reservations ADD CONSTRAINT `reservations_ibfk_1` FOREIGN KEY (id_evenement) REFERENCES evenements (id_evenement);
ALTER TABLE reservations ADD CONSTRAINT `reservations_ibfk_2` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur);
ALTER TABLE ressources_projet DROP FOREIGN KEY `fk_ressource_projet`;
ALTER TABLE ressources_projet CHANGE caracteristiques caracteristiques JSON DEFAULT NULL;
DROP INDEX idx_ressource_projet ON ressources_projet;
CREATE INDEX IDX_B2C582D176222944 ON ressources_projet (id_projet);
ALTER TABLE ressources_projet ADD CONSTRAINT `fk_ressource_projet` FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE;
DROP INDEX nom_role ON roles;
CREATE UNIQUE INDEX UNIQ_B63E2EC7A5B94004 ON roles (nom_role);
ALTER TABLE sprints DROP FOREIGN KEY `sprints_ibfk_1`;
ALTER TABLE sprints CHANGE id_projet id_projet INT DEFAULT NULL, CHANGE objectif objectif LONGTEXT DEFAULT NULL, CHANGE statut statut VARCHAR(255) DEFAULT 'planifie' NOT NULL;
DROP INDEX id_projet ON sprints;
CREATE INDEX IDX_4EE4697176222944 ON sprints (id_projet);
ALTER TABLE sprints ADD CONSTRAINT `sprints_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE;
ALTER TABLE userstory DROP FOREIGN KEY `userstory_ibfk_1`;
ALTER TABLE userstory DROP FOREIGN KEY `userstory_ibfk_2`;
ALTER TABLE userstory DROP FOREIGN KEY `userstory_ibfk_1`;
ALTER TABLE userstory DROP FOREIGN KEY `userstory_ibfk_2`;
ALTER TABLE userstory CHANGE id_userstory id_userstory INT NOT NULL, CHANGE id_projet id_projet INT DEFAULT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE story_points story_points INT NOT NULL, CHANGE priorite priorite VARCHAR(255) NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE date_creation date_creation DATETIME NOT NULL, CHANGE en_tant_que en_tant_que VARCHAR(255) NOT NULL, CHANGE je_veux je_veux VARCHAR(255) NOT NULL, CHANGE afin_de afin_de VARCHAR(255) NOT NULL, CHANGE criteres_acceptation criteres_acceptation LONGTEXT NOT NULL;
ALTER TABLE userstory ADD CONSTRAINT FK_CCF238EA76222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE;
ALTER TABLE userstory ADD CONSTRAINT FK_CCF238EAC9B7E05A FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE CASCADE;
DROP INDEX id_projet ON userstory;
CREATE INDEX IDX_CCF238EA76222944 ON userstory (id_projet);
DROP INDEX id_sprint ON userstory;
CREATE INDEX IDX_CCF238EAC9B7E05A ON userstory (id_sprint);
ALTER TABLE userstory ADD CONSTRAINT `userstory_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet);
ALTER TABLE userstory ADD CONSTRAINT `userstory_ibfk_2` FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint);
ALTER TABLE user_stories DROP FOREIGN KEY `fk_user_stories_membre_equipe`;
ALTER TABLE user_stories DROP FOREIGN KEY `user_stories_ibfk_2`;
ALTER TABLE user_stories DROP FOREIGN KEY `fk_user_stories_membre_equipe`;
ALTER TABLE user_stories DROP FOREIGN KEY `user_stories_ibfk_1`;
ALTER TABLE user_stories DROP FOREIGN KEY `user_stories_ibfk_2`;
ALTER TABLE user_stories CHANGE id_user_story id_user_story INT NOT NULL, CHANGE id_projet id_projet INT DEFAULT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE story_points story_points INT NOT NULL, CHANGE priorite priorite VARCHAR(255) NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE date_completion date_completion DATE NOT NULL, CHANGE criteres_acceptation criteres_acceptation LONGTEXT NOT NULL, CHANGE membre_nom membre_nom VARCHAR(100) NOT NULL, CHANGE date_debut date_debut DATE NOT NULL;
ALTER TABLE user_stories ADD CONSTRAINT FK_C4868355C9B7E05A FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE CASCADE;
ALTER TABLE user_stories ADD CONSTRAINT FK_C486835568FEC9 FOREIGN KEY (id_membre_equipe) REFERENCES membres_equipe (id_membre) ON DELETE CASCADE;
DROP INDEX id_projet ON user_stories;
CREATE INDEX IDX_C486835576222944 ON user_stories (id_projet);
DROP INDEX id_sprint ON user_stories;
CREATE INDEX IDX_C4868355C9B7E05A ON user_stories (id_sprint);
DROP INDEX fk_user_stories_membre_equipe ON user_stories;
CREATE INDEX IDX_C486835568FEC9 ON user_stories (id_membre_equipe);
ALTER TABLE user_stories ADD CONSTRAINT `fk_user_stories_membre_equipe` FOREIGN KEY (id_membre_equipe) REFERENCES membres_equipe (id_membre) ON DELETE SET NULL;
ALTER TABLE user_stories ADD CONSTRAINT `user_stories_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE;
ALTER TABLE user_stories ADD CONSTRAINT `user_stories_ibfk_2` FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE SET NULL;
DROP INDEX unique_assignment ON user_story_assignments;
ALTER TABLE user_story_assignments DROP FOREIGN KEY `user_story_assignments_ibfk_2`;
ALTER TABLE user_story_assignments CHANGE id_assignment id_assignment INT NOT NULL, CHANGE id_user_story id_user_story INT DEFAULT NULL, CHANGE id_membre_equipe id_membre_equipe INT DEFAULT NULL;
DROP INDEX id_membre_equipe ON user_story_assignments;
CREATE INDEX IDX_38BD834968FEC9 ON user_story_assignments (id_membre_equipe);
ALTER TABLE user_story_assignments ADD CONSTRAINT `user_story_assignments_ibfk_2` FOREIGN KEY (id_membre_equipe) REFERENCES membres_equipe (id_membre) ON DELETE CASCADE;
