<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260413231423 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE resource_reports (id INT AUTO_INCREMENT NOT NULL, reason VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, status VARCHAR(20) NOT NULL, id_ressource INT NOT NULL, id_utilisateur INT NOT NULL, INDEX IDX_ACBF40AD13AAF963 (id_ressource), INDEX IDX_ACBF40AD50EAE44 (id_utilisateur), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE resource_reports ADD CONSTRAINT FK_ACBF40AD13AAF963 FOREIGN KEY (id_ressource) REFERENCES ressources (id_ressource) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resource_reports ADD CONSTRAINT FK_ACBF40AD50EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('DROP INDEX idx_conversation_participants ON conversation_participants');
        $this->addSql('ALTER TABLE conversation_participants DROP FOREIGN KEY `conversation_participants_ibfk_2`');
        $this->addSql('ALTER TABLE conversation_participants CHANGE date_ajout date_ajout DATETIME NOT NULL, CHANGE est_archive est_archive TINYINT NOT NULL, CHANGE dernier_message_lu dernier_message_lu INT NOT NULL');
        $this->addSql('DROP INDEX id_utilisateur ON conversation_participants');
        $this->addSql('CREATE INDEX IDX_21821ED350EAE44 ON conversation_participants (id_utilisateur)');
        $this->addSql('ALTER TABLE conversation_participants ADD CONSTRAINT `conversation_participants_ibfk_2` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE criteres_evaluation CHANGE id_critere id_critere INT NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE poids poids INT NOT NULL, CHANGE actif actif TINYINT NOT NULL');
        $this->addSql('DROP INDEX unique_sprint_date ON daily_scrums');
        $this->addSql('ALTER TABLE daily_scrums CHANGE id_daily id_daily INT NOT NULL, CHANGE id_sprint id_sprint INT DEFAULT NULL, CHANGE commentaires commentaires LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE demandes_ressources DROP FOREIGN KEY `demandes_ressources_ibfk_1`');
        $this->addSql('ALTER TABLE demandes_ressources DROP FOREIGN KEY `demandes_ressources_ibfk_2`');
        $this->addSql('ALTER TABLE demandes_ressources DROP FOREIGN KEY `demandes_ressources_ibfk_1`');
        $this->addSql('ALTER TABLE demandes_ressources DROP FOREIGN KEY `demandes_ressources_ibfk_2`');
        $this->addSql('ALTER TABLE demandes_ressources CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE date_demande date_demande DATETIME NOT NULL');
        $this->addSql('ALTER TABLE demandes_ressources ADD CONSTRAINT FK_B57BECB213AAF963 FOREIGN KEY (id_ressource) REFERENCES ressources (id_ressource) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demandes_ressources ADD CONSTRAINT FK_B57BECB2D14DE5D1 FOREIGN KEY (id_entrepreneur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('DROP INDEX id_ressource ON demandes_ressources');
        $this->addSql('CREATE INDEX IDX_B57BECB213AAF963 ON demandes_ressources (id_ressource)');
        $this->addSql('DROP INDEX id_entrepreneur ON demandes_ressources');
        $this->addSql('CREATE INDEX IDX_B57BECB2D14DE5D1 ON demandes_ressources (id_entrepreneur)');
        $this->addSql('ALTER TABLE demandes_ressources ADD CONSTRAINT `demandes_ressources_ibfk_1` FOREIGN KEY (id_ressource) REFERENCES ressources (id_ressource)');
        $this->addSql('ALTER TABLE demandes_ressources ADD CONSTRAINT `demandes_ressources_ibfk_2` FOREIGN KEY (id_entrepreneur) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('ALTER TABLE demandes_verification DROP FOREIGN KEY `demandes_verification_ibfk_2`');
        $this->addSql('DROP INDEX idx_date ON demandes_verification');
        $this->addSql('DROP INDEX idx_statut ON demandes_verification');
        $this->addSql('ALTER TABLE demandes_verification DROP FOREIGN KEY `demandes_verification_ibfk_1`');
        $this->addSql('ALTER TABLE demandes_verification DROP FOREIGN KEY `demandes_verification_ibfk_2`');
        $this->addSql('ALTER TABLE demandes_verification CHANGE id_utilisateur id_utilisateur INT DEFAULT NULL, CHANGE type_role type_role VARCHAR(50) NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE raison_demande raison_demande LONGTEXT NOT NULL, CHANGE document_justificatif document_justificatif VARCHAR(255) NOT NULL, CHANGE date_demande date_demande DATETIME NOT NULL, CHANGE date_traitement date_traitement DATETIME NOT NULL, CHANGE commentaire_admin commentaire_admin LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE demandes_verification ADD CONSTRAINT FK_57BC1FE7C9DD9712 FOREIGN KEY (id_admin_traitant) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_utilisateur ON demandes_verification');
        $this->addSql('CREATE INDEX IDX_57BC1FE750EAE44 ON demandes_verification (id_utilisateur)');
        $this->addSql('DROP INDEX id_admin_traitant ON demandes_verification');
        $this->addSql('CREATE INDEX IDX_57BC1FE7C9DD9712 ON demandes_verification (id_admin_traitant)');
        $this->addSql('ALTER TABLE demandes_verification ADD CONSTRAINT `demandes_verification_ibfk_1` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demandes_verification ADD CONSTRAINT `demandes_verification_ibfk_2` FOREIGN KEY (id_admin_traitant) REFERENCES utilisateurs (id_utilisateur) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE evaluations_projet DROP FOREIGN KEY `evaluations_projet_ibfk_1`');
        $this->addSql('ALTER TABLE evaluations_projet DROP FOREIGN KEY `evaluations_projet_ibfk_2`');
        $this->addSql('ALTER TABLE evaluations_projet DROP FOREIGN KEY `evaluations_projet_ibfk_1`');
        $this->addSql('ALTER TABLE evaluations_projet DROP FOREIGN KEY `evaluations_projet_ibfk_2`');
        $this->addSql('ALTER TABLE evaluations_projet CHANGE note_originalite note_originalite INT NOT NULL, CHANGE note_faisabilite note_faisabilite INT NOT NULL, CHANGE note_impact note_impact INT NOT NULL, CHANGE note_clarte note_clarte INT NOT NULL, CHANGE note_budget note_budget INT NOT NULL, CHANGE commentaire commentaire LONGTEXT NOT NULL, CHANGE date_evaluation date_evaluation DATETIME NOT NULL');
        $this->addSql('ALTER TABLE evaluations_projet ADD CONSTRAINT FK_24EC14B976222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluations_projet ADD CONSTRAINT FK_24EC14B9668B4C46 FOREIGN KEY (id_admin) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('DROP INDEX id_projet ON evaluations_projet');
        $this->addSql('CREATE INDEX IDX_24EC14B976222944 ON evaluations_projet (id_projet)');
        $this->addSql('DROP INDEX id_admin ON evaluations_projet');
        $this->addSql('CREATE INDEX IDX_24EC14B9668B4C46 ON evaluations_projet (id_admin)');
        $this->addSql('ALTER TABLE evaluations_projet ADD CONSTRAINT `evaluations_projet_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet)');
        $this->addSql('ALTER TABLE evaluations_projet ADD CONSTRAINT `evaluations_projet_ibfk_2` FOREIGN KEY (id_admin) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('ALTER TABLE evenements CHANGE titre titre VARCHAR(150) NOT NULL, CHANGE date_evenement date_evenement DATE NOT NULL, CHANGE lieu lieu VARCHAR(150) NOT NULL, CHANGE capacite capacite INT NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE prix prix DOUBLE PRECISION NOT NULL');
        $this->addSql('DROP INDEX idx_date_connexion ON historique_connexions');
        $this->addSql('DROP INDEX idx_adresse_ip ON historique_connexions');
        $this->addSql('ALTER TABLE historique_connexions DROP FOREIGN KEY `historique_connexions_ibfk_1`');
        $this->addSql('ALTER TABLE historique_connexions CHANGE id_utilisateur id_utilisateur INT DEFAULT NULL, CHANGE ville ville VARCHAR(100) NOT NULL, CHANGE pays pays VARCHAR(100) NOT NULL, CHANGE region region VARCHAR(100) NOT NULL, CHANGE code_postal code_postal VARCHAR(20) NOT NULL, CHANGE timezone timezone VARCHAR(50) NOT NULL, CHANGE date_connexion date_connexion DATETIME NOT NULL, CHANGE user_agent user_agent LONGTEXT NOT NULL');
        $this->addSql('DROP INDEX idx_utilisateur ON historique_connexions');
        $this->addSql('CREATE INDEX IDX_9A70C17450EAE44 ON historique_connexions (id_utilisateur)');
        $this->addSql('ALTER TABLE historique_connexions ADD CONSTRAINT `historique_connexions_ibfk_1` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lignes_commande CHANGE id_commande id_commande INT DEFAULT NULL, CHANGE id_ressource id_ressource INT DEFAULT NULL, CHANGE quantite quantite INT NOT NULL, CHANGE date_deb date_deb DATE NOT NULL, CHANGE date_fin date_fin DATE NOT NULL, CHANGE prix_ligne prix_ligne VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE lignes_commande ADD CONSTRAINT FK_DAAE0FCB3E314AE8 FOREIGN KEY (id_commande) REFERENCES commandes (id_commande) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lignes_commande ADD CONSTRAINT FK_DAAE0FCB13AAF963 FOREIGN KEY (id_ressource) REFERENCES ressources (id_ressource) ON DELETE CASCADE');
        $this->addSql('DROP INDEX id_commande ON lignes_commande');
        $this->addSql('CREATE INDEX IDX_DAAE0FCB3E314AE8 ON lignes_commande (id_commande)');
        $this->addSql('DROP INDEX id_ressource ON lignes_commande');
        $this->addSql('CREATE INDEX IDX_DAAE0FCB13AAF963 ON lignes_commande (id_ressource)');
        $this->addSql('ALTER TABLE membres_equipe DROP FOREIGN KEY `membres_equipe_ibfk_1`');
        $this->addSql('ALTER TABLE membres_equipe DROP FOREIGN KEY `membres_equipe_ibfk_2`');
        $this->addSql('ALTER TABLE membres_equipe DROP FOREIGN KEY `membres_equipe_ibfk_1`');
        $this->addSql('ALTER TABLE membres_equipe DROP FOREIGN KEY `membres_equipe_ibfk_2`');
        $this->addSql('ALTER TABLE membres_equipe ADD CONSTRAINT FK_C184283276222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE membres_equipe ADD CONSTRAINT FK_C184283250EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('DROP INDEX id_projet ON membres_equipe');
        $this->addSql('CREATE INDEX IDX_C184283276222944 ON membres_equipe (id_projet)');
        $this->addSql('DROP INDEX id_utilisateur ON membres_equipe');
        $this->addSql('CREATE INDEX IDX_C184283250EAE44 ON membres_equipe (id_utilisateur)');
        $this->addSql('ALTER TABLE membres_equipe ADD CONSTRAINT `membres_equipe_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet)');
        $this->addSql('ALTER TABLE membres_equipe ADD CONSTRAINT `membres_equipe_ibfk_2` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('DROP INDEX idx_messages_conversation ON messages');
        $this->addSql('ALTER TABLE messages DROP FOREIGN KEY `messages_ibfk_2`');
        $this->addSql('ALTER TABLE messages CHANGE contenu contenu LONGTEXT NOT NULL, CHANGE date_envoi date_envoi DATETIME NOT NULL, CHANGE est_lu est_lu TINYINT NOT NULL, CHANGE est_modifie est_modifie TINYINT NOT NULL, CHANGE est_supprime est_supprime TINYINT NOT NULL, CHANGE type_contenu type_contenu VARCHAR(255) NOT NULL, CHANGE piece_jointe piece_jointe VARCHAR(255) NOT NULL');
        $this->addSql('DROP INDEX id_expediteur ON messages');
        $this->addSql('CREATE INDEX IDX_DB021E96E2E4F59 ON messages (id_expediteur)');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT `messages_ibfk_2` FOREIGN KEY (id_expediteur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_expiration ON password_reset_tokens');
        $this->addSql('DROP INDEX token ON password_reset_tokens');
        $this->addSql('DROP INDEX idx_token ON password_reset_tokens');
        $this->addSql('ALTER TABLE password_reset_tokens DROP FOREIGN KEY `password_reset_tokens_ibfk_1`');
        $this->addSql('ALTER TABLE password_reset_tokens CHANGE id_utilisateur id_utilisateur INT DEFAULT NULL, CHANGE date_creation date_creation DATETIME NOT NULL, CHANGE date_expiration date_expiration DATETIME NOT NULL, CHANGE utilise utilise TINYINT NOT NULL');
        $this->addSql('DROP INDEX id_utilisateur ON password_reset_tokens');
        $this->addSql('CREATE INDEX IDX_3967A21650EAE44 ON password_reset_tokens (id_utilisateur)');
        $this->addSql('ALTER TABLE password_reset_tokens ADD CONSTRAINT `password_reset_tokens_ibfk_1` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE projets DROP FOREIGN KEY `projets_ibfk_1`');
        $this->addSql('ALTER TABLE projets DROP FOREIGN KEY `projets_ibfk_1`');
        $this->addSql('ALTER TABLE projets CHANGE description description LONGTEXT DEFAULT NULL, CHANGE objectifs objectifs LONGTEXT DEFAULT NULL, CHANGE etat etat VARCHAR(255) DEFAULT \'En attente\' NOT NULL, CHANGE commentaire_admin commentaire_admin LONGTEXT DEFAULT NULL, CHANGE date_soumission date_soumission DATETIME DEFAULT NULL, CHANGE note_moyenne note_moyenne DOUBLE PRECISION DEFAULT NULL, CHANGE evaluation_automatique evaluation_automatique TINYINT DEFAULT NULL');
        $this->addSql('ALTER TABLE projets ADD CONSTRAINT FK_B454C1DBD14DE5D1 FOREIGN KEY (id_entrepreneur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('DROP INDEX id_entrepreneur ON projets');
        $this->addSql('CREATE INDEX IDX_B454C1DBD14DE5D1 ON projets (id_entrepreneur)');
        $this->addSql('ALTER TABLE projets ADD CONSTRAINT `projets_ibfk_1` FOREIGN KEY (id_entrepreneur) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('ALTER TABLE reclamation_commentaires DROP FOREIGN KEY `fk_commentaire_auteur`');
        $this->addSql('ALTER TABLE reclamation_commentaires DROP FOREIGN KEY `reclamation_commentaires_ibfk_1`');
        $this->addSql('ALTER TABLE reclamation_commentaires CHANGE id_reclamation id_reclamation INT DEFAULT NULL, CHANGE id_auteur id_auteur INT DEFAULT NULL, CHANGE commentaire commentaire LONGTEXT NOT NULL, CHANGE date_commentaire date_commentaire DATETIME NOT NULL');
        $this->addSql('DROP INDEX id_reclamation ON reclamation_commentaires');
        $this->addSql('CREATE INDEX IDX_5EAA37A6D672A9F3 ON reclamation_commentaires (id_reclamation)');
        $this->addSql('DROP INDEX fk_commentaire_auteur ON reclamation_commentaires');
        $this->addSql('CREATE INDEX IDX_5EAA37A6236D04AD ON reclamation_commentaires (id_auteur)');
        $this->addSql('ALTER TABLE reclamation_commentaires ADD CONSTRAINT `fk_commentaire_auteur` FOREIGN KEY (id_auteur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reclamation_commentaires ADD CONSTRAINT `reclamation_commentaires_ibfk_1` FOREIGN KEY (id_reclamation) REFERENCES reclamations (id_reclamation) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reclamations DROP FOREIGN KEY `reclamations_ibfk_1`');
        $this->addSql('ALTER TABLE reclamations DROP adresse, DROP latitude, DROP longitude, DROP emotion, DROP reponse_admin, DROP date_modification, CHANGE id_utilisateur id_utilisateur INT NOT NULL, CHANGE sujet sujet VARCHAR(150) NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE statut statut VARCHAR(20) NOT NULL, CHANGE date_creation date_creation DATETIME NOT NULL');
        $this->addSql('DROP INDEX id_utilisateur ON reclamations');
        $this->addSql('CREATE INDEX IDX_1CAD6B7650EAE44 ON reclamations (id_utilisateur)');
        $this->addSql('ALTER TABLE reclamations ADD CONSTRAINT `reclamations_ibfk_1` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('ALTER TABLE reservations DROP FOREIGN KEY `reservations_ibfk_1`');
        $this->addSql('ALTER TABLE reservations DROP FOREIGN KEY `reservations_ibfk_2`');
        $this->addSql('ALTER TABLE reservations DROP FOREIGN KEY `reservations_ibfk_1`');
        $this->addSql('ALTER TABLE reservations DROP FOREIGN KEY `reservations_ibfk_2`');
        $this->addSql('ALTER TABLE reservations CHANGE date_reservation date_reservation DATETIME NOT NULL');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA2398B13D439 FOREIGN KEY (id_evenement) REFERENCES evenements (id_evenement) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA23950EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('DROP INDEX id_evenement ON reservations');
        $this->addSql('CREATE INDEX IDX_4DA2398B13D439 ON reservations (id_evenement)');
        $this->addSql('DROP INDEX id_utilisateur ON reservations');
        $this->addSql('CREATE INDEX IDX_4DA23950EAE44 ON reservations (id_utilisateur)');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT `reservations_ibfk_1` FOREIGN KEY (id_evenement) REFERENCES evenements (id_evenement)');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT `reservations_ibfk_2` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('ALTER TABLE ressources DROP FOREIGN KEY `ressources_ibfk_1`');
        $this->addSql('ALTER TABLE ressources DROP FOREIGN KEY `ressources_ibfk_1`');
        $this->addSql('ALTER TABLE ressources ADD is_banned TINYINT NOT NULL, ADD moderation_score INT NOT NULL, ADD moderation_reason VARCHAR(255) DEFAULT NULL, CHANGE nom nom VARCHAR(150) NOT NULL, CHANGE offre offre VARCHAR(30) NOT NULL, CHANGE type_r type_r VARCHAR(30) NOT NULL, CHANGE image_r image_r VARCHAR(255) NOT NULL, CHANGE prix_achat prix_achat DOUBLE PRECISION NOT NULL, CHANGE disponibilite disponibilite TINYINT NOT NULL, CHANGE prix_louer prix_louer DOUBLE PRECISION NOT NULL, CHANGE unite_louer unite_louer VARCHAR(30) NOT NULL, CHANGE quantite quantite INT NOT NULL, CHANGE etat etat VARCHAR(30) NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE ressources ADD CONSTRAINT FK_6A2CD5C72E8C07C5 FOREIGN KEY (id_fournisseur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('DROP INDEX id_fournisseur ON ressources');
        $this->addSql('CREATE INDEX IDX_6A2CD5C72E8C07C5 ON ressources (id_fournisseur)');
        $this->addSql('ALTER TABLE ressources ADD CONSTRAINT `ressources_ibfk_1` FOREIGN KEY (id_fournisseur) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('DROP INDEX nom_role ON roles');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B63E2EC7A5B94004 ON roles (nom_role)');
        $this->addSql('ALTER TABLE sprints DROP FOREIGN KEY `sprints_ibfk_1`');
        $this->addSql('ALTER TABLE sprints CHANGE id_projet id_projet INT DEFAULT NULL, CHANGE objectif objectif LONGTEXT NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE capacite_equipe capacite_equipe INT NOT NULL, CHANGE velocite_prevue velocite_prevue INT NOT NULL, CHANGE velocite_reelle velocite_reelle INT NOT NULL');
        $this->addSql('DROP INDEX id_projet ON sprints');
        $this->addSql('CREATE INDEX IDX_4EE4697176222944 ON sprints (id_projet)');
        $this->addSql('ALTER TABLE sprints ADD CONSTRAINT `sprints_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE taches DROP FOREIGN KEY `taches_ibfk_1`');
        $this->addSql('ALTER TABLE taches DROP FOREIGN KEY `taches_ibfk_2`');
        $this->addSql('ALTER TABLE taches DROP FOREIGN KEY `taches_ibfk_3`');
        $this->addSql('ALTER TABLE taches DROP FOREIGN KEY `taches_ibfk_1`');
        $this->addSql('ALTER TABLE taches DROP FOREIGN KEY `taches_ibfk_2`');
        $this->addSql('ALTER TABLE taches DROP FOREIGN KEY `taches_ibfk_3`');
        $this->addSql('ALTER TABLE taches CHANGE description description LONGTEXT DEFAULT NULL, CHANGE statut statut VARCHAR(255) DEFAULT \'À faire\' NOT NULL');
        $this->addSql('ALTER TABLE taches ADD CONSTRAINT FK_3BF2CD9876222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE taches ADD CONSTRAINT FK_3BF2CD98C9B7E05A FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE taches ADD CONSTRAINT FK_3BF2CD984A40C0F0 FOREIGN KEY (id_responsable) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('DROP INDEX id_projet ON taches');
        $this->addSql('CREATE INDEX IDX_3BF2CD9876222944 ON taches (id_projet)');
        $this->addSql('DROP INDEX id_sprint ON taches');
        $this->addSql('CREATE INDEX IDX_3BF2CD98C9B7E05A ON taches (id_sprint)');
        $this->addSql('DROP INDEX id_responsable ON taches');
        $this->addSql('CREATE INDEX IDX_3BF2CD984A40C0F0 ON taches (id_responsable)');
        $this->addSql('ALTER TABLE taches ADD CONSTRAINT `taches_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet)');
        $this->addSql('ALTER TABLE taches ADD CONSTRAINT `taches_ibfk_2` FOREIGN KEY (id_responsable) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('ALTER TABLE taches ADD CONSTRAINT `taches_ibfk_3` FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_stories DROP FOREIGN KEY `fk_user_stories_membre_equipe`');
        $this->addSql('ALTER TABLE user_stories DROP FOREIGN KEY `user_stories_ibfk_2`');
        $this->addSql('ALTER TABLE user_stories DROP FOREIGN KEY `fk_user_stories_membre_equipe`');
        $this->addSql('ALTER TABLE user_stories DROP FOREIGN KEY `user_stories_ibfk_1`');
        $this->addSql('ALTER TABLE user_stories DROP FOREIGN KEY `user_stories_ibfk_2`');
        $this->addSql('ALTER TABLE user_stories CHANGE id_user_story id_user_story INT NOT NULL, CHANGE id_projet id_projet INT DEFAULT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE story_points story_points INT NOT NULL, CHANGE priorite priorite VARCHAR(255) NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE date_completion date_completion DATE NOT NULL, CHANGE criteres_acceptation criteres_acceptation LONGTEXT NOT NULL, CHANGE membre_nom membre_nom VARCHAR(100) NOT NULL, CHANGE date_debut date_debut DATE NOT NULL');
        $this->addSql('ALTER TABLE user_stories ADD CONSTRAINT FK_C4868355C9B7E05A FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_stories ADD CONSTRAINT FK_C486835568FEC9 FOREIGN KEY (id_membre_equipe) REFERENCES membres_equipe (id_membre) ON DELETE CASCADE');
        $this->addSql('DROP INDEX id_projet ON user_stories');
        $this->addSql('CREATE INDEX IDX_C486835576222944 ON user_stories (id_projet)');
        $this->addSql('DROP INDEX id_sprint ON user_stories');
        $this->addSql('CREATE INDEX IDX_C4868355C9B7E05A ON user_stories (id_sprint)');
        $this->addSql('DROP INDEX fk_user_stories_membre_equipe ON user_stories');
        $this->addSql('CREATE INDEX IDX_C486835568FEC9 ON user_stories (id_membre_equipe)');
        $this->addSql('ALTER TABLE user_stories ADD CONSTRAINT `fk_user_stories_membre_equipe` FOREIGN KEY (id_membre_equipe) REFERENCES membres_equipe (id_membre) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_stories ADD CONSTRAINT `user_stories_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_stories ADD CONSTRAINT `user_stories_ibfk_2` FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE SET NULL');
        $this->addSql('DROP INDEX unique_assignment ON user_story_assignments');
        $this->addSql('ALTER TABLE user_story_assignments DROP FOREIGN KEY `user_story_assignments_ibfk_2`');
        $this->addSql('ALTER TABLE user_story_assignments CHANGE id_assignment id_assignment INT NOT NULL, CHANGE id_user_story id_user_story INT DEFAULT NULL, CHANGE id_membre_equipe id_membre_equipe INT DEFAULT NULL');
        $this->addSql('DROP INDEX id_membre_equipe ON user_story_assignments');
        $this->addSql('CREATE INDEX IDX_38BD834968FEC9 ON user_story_assignments (id_membre_equipe)');
        $this->addSql('ALTER TABLE user_story_assignments ADD CONSTRAINT `user_story_assignments_ibfk_2` FOREIGN KEY (id_membre_equipe) REFERENCES membres_equipe (id_membre) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE userstory DROP FOREIGN KEY `userstory_ibfk_1`');
        $this->addSql('ALTER TABLE userstory DROP FOREIGN KEY `userstory_ibfk_2`');
        $this->addSql('ALTER TABLE userstory DROP FOREIGN KEY `userstory_ibfk_1`');
        $this->addSql('ALTER TABLE userstory DROP FOREIGN KEY `userstory_ibfk_2`');
        $this->addSql('ALTER TABLE userstory CHANGE id_userstory id_userstory INT NOT NULL, CHANGE id_projet id_projet INT DEFAULT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE story_points story_points INT NOT NULL, CHANGE priorite priorite VARCHAR(255) NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE date_creation date_creation DATETIME NOT NULL, CHANGE en_tant_que en_tant_que VARCHAR(255) NOT NULL, CHANGE je_veux je_veux VARCHAR(255) NOT NULL, CHANGE afin_de afin_de VARCHAR(255) NOT NULL, CHANGE criteres_acceptation criteres_acceptation LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE userstory ADD CONSTRAINT FK_CCF238EA76222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE userstory ADD CONSTRAINT FK_CCF238EAC9B7E05A FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE CASCADE');
        $this->addSql('DROP INDEX id_projet ON userstory');
        $this->addSql('CREATE INDEX IDX_CCF238EA76222944 ON userstory (id_projet)');
        $this->addSql('DROP INDEX id_sprint ON userstory');
        $this->addSql('CREATE INDEX IDX_CCF238EAC9B7E05A ON userstory (id_sprint)');
        $this->addSql('ALTER TABLE userstory ADD CONSTRAINT `userstory_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet)');
        $this->addSql('ALTER TABLE userstory ADD CONSTRAINT `userstory_ibfk_2` FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint)');
        $this->addSql('ALTER TABLE utilisateurs DROP FOREIGN KEY `utilisateurs_ibfk_1`');
        $this->addSql('ALTER TABLE utilisateurs CHANGE nom nom VARCHAR(100) NOT NULL, CHANGE bio bio LONGTEXT DEFAULT NULL, CHANGE competences competences LONGTEXT DEFAULT NULL, CHANGE date_inscription date_inscription DATETIME NOT NULL, CHANGE badge_verifie badge_verifie TINYINT DEFAULT 0 NOT NULL, CHANGE profil_complet profil_complet TINYINT DEFAULT 0 NOT NULL, CHANGE actif actif TINYINT DEFAULT 1 NOT NULL, CHANGE adresse adresse VARCHAR(255) DEFAULT NULL, CHANGE latitude latitude DOUBLE PRECISION DEFAULT NULL, CHANGE longitude longitude DOUBLE PRECISION DEFAULT NULL, CHANGE badge_verification badge_verification VARCHAR(100) DEFAULT NULL, CHANGE avatar_url avatar_url VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP INDEX email ON utilisateurs');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_497B315EE7927C74 ON utilisateurs (email)');
        $this->addSql('DROP INDEX id_role ON utilisateurs');
        $this->addSql('CREATE INDEX IDX_497B315EDC499668 ON utilisateurs (id_role)');
        $this->addSql('ALTER TABLE utilisateurs ADD CONSTRAINT `utilisateurs_ibfk_1` FOREIGN KEY (id_role) REFERENCES roles (id_role)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE resource_reports DROP FOREIGN KEY FK_ACBF40AD13AAF963');
        $this->addSql('ALTER TABLE resource_reports DROP FOREIGN KEY FK_ACBF40AD50EAE44');
        $this->addSql('DROP TABLE resource_reports');
        $this->addSql('ALTER TABLE conversation_participants DROP FOREIGN KEY FK_21821ED350EAE44');
        $this->addSql('ALTER TABLE conversation_participants CHANGE date_ajout date_ajout DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE est_archive est_archive TINYINT DEFAULT 0, CHANGE dernier_message_lu dernier_message_lu INT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_conversation_participants ON conversation_participants (id_conversation, id_utilisateur)');
        $this->addSql('DROP INDEX idx_21821ed350eae44 ON conversation_participants');
        $this->addSql('CREATE INDEX id_utilisateur ON conversation_participants (id_utilisateur)');
        $this->addSql('ALTER TABLE conversation_participants ADD CONSTRAINT FK_21821ED350EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE criteres_evaluation CHANGE id_critere id_critere INT AUTO_INCREMENT NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE poids poids INT DEFAULT 1, CHANGE actif actif TINYINT DEFAULT 1');
        $this->addSql('ALTER TABLE daily_scrums CHANGE id_daily id_daily INT AUTO_INCREMENT NOT NULL, CHANGE commentaires commentaires TEXT DEFAULT NULL, CHANGE id_sprint id_sprint INT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX unique_sprint_date ON daily_scrums (id_sprint, date)');
        $this->addSql('ALTER TABLE demandes_ressources DROP FOREIGN KEY FK_B57BECB213AAF963');
        $this->addSql('ALTER TABLE demandes_ressources DROP FOREIGN KEY FK_B57BECB2D14DE5D1');
        $this->addSql('ALTER TABLE demandes_ressources DROP FOREIGN KEY FK_B57BECB213AAF963');
        $this->addSql('ALTER TABLE demandes_ressources DROP FOREIGN KEY FK_B57BECB2D14DE5D1');
        $this->addSql('ALTER TABLE demandes_ressources CHANGE statut statut ENUM(\'En attente\', \'Acceptée\', \'Refusée\') DEFAULT \'En attente\', CHANGE date_demande date_demande DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE demandes_ressources ADD CONSTRAINT `demandes_ressources_ibfk_1` FOREIGN KEY (id_ressource) REFERENCES ressources (id_ressource)');
        $this->addSql('ALTER TABLE demandes_ressources ADD CONSTRAINT `demandes_ressources_ibfk_2` FOREIGN KEY (id_entrepreneur) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('DROP INDEX idx_b57becb213aaf963 ON demandes_ressources');
        $this->addSql('CREATE INDEX id_ressource ON demandes_ressources (id_ressource)');
        $this->addSql('DROP INDEX idx_b57becb2d14de5d1 ON demandes_ressources');
        $this->addSql('CREATE INDEX id_entrepreneur ON demandes_ressources (id_entrepreneur)');
        $this->addSql('ALTER TABLE demandes_ressources ADD CONSTRAINT FK_B57BECB213AAF963 FOREIGN KEY (id_ressource) REFERENCES ressources (id_ressource) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demandes_ressources ADD CONSTRAINT FK_B57BECB2D14DE5D1 FOREIGN KEY (id_entrepreneur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demandes_verification DROP FOREIGN KEY FK_57BC1FE7C9DD9712');
        $this->addSql('ALTER TABLE demandes_verification DROP FOREIGN KEY FK_57BC1FE750EAE44');
        $this->addSql('ALTER TABLE demandes_verification DROP FOREIGN KEY FK_57BC1FE7C9DD9712');
        $this->addSql('ALTER TABLE demandes_verification CHANGE type_role type_role VARCHAR(50) DEFAULT \'Candidat\' NOT NULL, CHANGE statut statut ENUM(\'en_attente\', \'approuvee\', \'refusee\') DEFAULT \'en_attente\', CHANGE raison_demande raison_demande TEXT DEFAULT NULL, CHANGE document_justificatif document_justificatif VARCHAR(255) DEFAULT NULL, CHANGE date_demande date_demande DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE date_traitement date_traitement DATETIME DEFAULT NULL, CHANGE commentaire_admin commentaire_admin TEXT DEFAULT NULL, CHANGE id_utilisateur id_utilisateur INT NOT NULL');
        $this->addSql('ALTER TABLE demandes_verification ADD CONSTRAINT `demandes_verification_ibfk_2` FOREIGN KEY (id_admin_traitant) REFERENCES utilisateurs (id_utilisateur) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX idx_date ON demandes_verification (date_demande)');
        $this->addSql('CREATE INDEX idx_statut ON demandes_verification (statut)');
        $this->addSql('DROP INDEX idx_57bc1fe7c9dd9712 ON demandes_verification');
        $this->addSql('CREATE INDEX id_admin_traitant ON demandes_verification (id_admin_traitant)');
        $this->addSql('DROP INDEX idx_57bc1fe750eae44 ON demandes_verification');
        $this->addSql('CREATE INDEX idx_utilisateur ON demandes_verification (id_utilisateur)');
        $this->addSql('ALTER TABLE demandes_verification ADD CONSTRAINT FK_57BC1FE750EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demandes_verification ADD CONSTRAINT FK_57BC1FE7C9DD9712 FOREIGN KEY (id_admin_traitant) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluations_projet DROP FOREIGN KEY FK_24EC14B976222944');
        $this->addSql('ALTER TABLE evaluations_projet DROP FOREIGN KEY FK_24EC14B9668B4C46');
        $this->addSql('ALTER TABLE evaluations_projet DROP FOREIGN KEY FK_24EC14B976222944');
        $this->addSql('ALTER TABLE evaluations_projet DROP FOREIGN KEY FK_24EC14B9668B4C46');
        $this->addSql('ALTER TABLE evaluations_projet CHANGE note_originalite note_originalite INT DEFAULT NULL, CHANGE note_faisabilite note_faisabilite INT DEFAULT NULL, CHANGE note_impact note_impact INT DEFAULT NULL, CHANGE note_clarte note_clarte INT DEFAULT NULL, CHANGE note_budget note_budget INT DEFAULT NULL, CHANGE commentaire commentaire TEXT DEFAULT NULL, CHANGE date_evaluation date_evaluation DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE evaluations_projet ADD CONSTRAINT `evaluations_projet_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet)');
        $this->addSql('ALTER TABLE evaluations_projet ADD CONSTRAINT `evaluations_projet_ibfk_2` FOREIGN KEY (id_admin) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('DROP INDEX idx_24ec14b9668b4c46 ON evaluations_projet');
        $this->addSql('CREATE INDEX id_admin ON evaluations_projet (id_admin)');
        $this->addSql('DROP INDEX idx_24ec14b976222944 ON evaluations_projet');
        $this->addSql('CREATE INDEX id_projet ON evaluations_projet (id_projet)');
        $this->addSql('ALTER TABLE evaluations_projet ADD CONSTRAINT FK_24EC14B976222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluations_projet ADD CONSTRAINT FK_24EC14B9668B4C46 FOREIGN KEY (id_admin) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evenements CHANGE titre titre VARCHAR(150) DEFAULT NULL, CHANGE date_evenement date_evenement DATE DEFAULT NULL, CHANGE lieu lieu VARCHAR(150) DEFAULT NULL, CHANGE capacite capacite INT DEFAULT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE prix prix NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE historique_connexions DROP FOREIGN KEY FK_9A70C17450EAE44');
        $this->addSql('ALTER TABLE historique_connexions CHANGE ville ville VARCHAR(100) DEFAULT NULL, CHANGE pays pays VARCHAR(100) DEFAULT NULL, CHANGE region region VARCHAR(100) DEFAULT NULL, CHANGE code_postal code_postal VARCHAR(20) DEFAULT NULL, CHANGE timezone timezone VARCHAR(50) DEFAULT NULL, CHANGE date_connexion date_connexion DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE user_agent user_agent TEXT DEFAULT NULL, CHANGE id_utilisateur id_utilisateur INT NOT NULL');
        $this->addSql('CREATE INDEX idx_date_connexion ON historique_connexions (date_connexion)');
        $this->addSql('CREATE INDEX idx_adresse_ip ON historique_connexions (adresse_ip)');
        $this->addSql('DROP INDEX idx_9a70c17450eae44 ON historique_connexions');
        $this->addSql('CREATE INDEX idx_utilisateur ON historique_connexions (id_utilisateur)');
        $this->addSql('ALTER TABLE historique_connexions ADD CONSTRAINT FK_9A70C17450EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lignes_commande DROP FOREIGN KEY FK_DAAE0FCB3E314AE8');
        $this->addSql('ALTER TABLE lignes_commande DROP FOREIGN KEY FK_DAAE0FCB13AAF963');
        $this->addSql('ALTER TABLE lignes_commande DROP FOREIGN KEY FK_DAAE0FCB3E314AE8');
        $this->addSql('ALTER TABLE lignes_commande DROP FOREIGN KEY FK_DAAE0FCB13AAF963');
        $this->addSql('ALTER TABLE lignes_commande CHANGE quantite quantite INT DEFAULT 1 NOT NULL, CHANGE date_deb date_deb DATE DEFAULT NULL, CHANGE date_fin date_fin DATE DEFAULT NULL, CHANGE prix_ligne prix_ligne FLOAT DEFAULT NULL, CHANGE id_commande id_commande INT NOT NULL, CHANGE id_ressource id_ressource INT NOT NULL');
        $this->addSql('DROP INDEX idx_daae0fcb3e314ae8 ON lignes_commande');
        $this->addSql('CREATE INDEX id_commande ON lignes_commande (id_commande)');
        $this->addSql('DROP INDEX idx_daae0fcb13aaf963 ON lignes_commande');
        $this->addSql('CREATE INDEX id_ressource ON lignes_commande (id_ressource)');
        $this->addSql('ALTER TABLE lignes_commande ADD CONSTRAINT FK_DAAE0FCB3E314AE8 FOREIGN KEY (id_commande) REFERENCES commandes (id_commande) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lignes_commande ADD CONSTRAINT FK_DAAE0FCB13AAF963 FOREIGN KEY (id_ressource) REFERENCES ressources (id_ressource) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE membres_equipe DROP FOREIGN KEY FK_C184283276222944');
        $this->addSql('ALTER TABLE membres_equipe DROP FOREIGN KEY FK_C184283250EAE44');
        $this->addSql('ALTER TABLE membres_equipe DROP FOREIGN KEY FK_C184283276222944');
        $this->addSql('ALTER TABLE membres_equipe DROP FOREIGN KEY FK_C184283250EAE44');
        $this->addSql('ALTER TABLE membres_equipe ADD CONSTRAINT `membres_equipe_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet)');
        $this->addSql('ALTER TABLE membres_equipe ADD CONSTRAINT `membres_equipe_ibfk_2` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('DROP INDEX idx_c184283276222944 ON membres_equipe');
        $this->addSql('CREATE INDEX id_projet ON membres_equipe (id_projet)');
        $this->addSql('DROP INDEX idx_c184283250eae44 ON membres_equipe');
        $this->addSql('CREATE INDEX id_utilisateur ON membres_equipe (id_utilisateur)');
        $this->addSql('ALTER TABLE membres_equipe ADD CONSTRAINT FK_C184283276222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE membres_equipe ADD CONSTRAINT FK_C184283250EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE messages DROP FOREIGN KEY FK_DB021E96E2E4F59');
        $this->addSql('ALTER TABLE messages CHANGE contenu contenu TEXT NOT NULL, CHANGE date_envoi date_envoi DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE est_lu est_lu TINYINT DEFAULT 0, CHANGE est_modifie est_modifie TINYINT DEFAULT 0, CHANGE est_supprime est_supprime TINYINT DEFAULT 0, CHANGE type_contenu type_contenu ENUM(\'texte\', \'image\', \'fichier\') DEFAULT \'texte\', CHANGE piece_jointe piece_jointe VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_messages_conversation ON messages (id_conversation, date_envoi)');
        $this->addSql('DROP INDEX idx_db021e96e2e4f59 ON messages');
        $this->addSql('CREATE INDEX id_expediteur ON messages (id_expediteur)');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96E2E4F59 FOREIGN KEY (id_expediteur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE password_reset_tokens DROP FOREIGN KEY FK_3967A21650EAE44');
        $this->addSql('ALTER TABLE password_reset_tokens CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE date_expiration date_expiration DATETIME DEFAULT NULL, CHANGE utilise utilise TINYINT DEFAULT 0, CHANGE id_utilisateur id_utilisateur INT NOT NULL');
        $this->addSql('CREATE INDEX idx_expiration ON password_reset_tokens (date_expiration)');
        $this->addSql('CREATE UNIQUE INDEX token ON password_reset_tokens (token)');
        $this->addSql('CREATE INDEX idx_token ON password_reset_tokens (token)');
        $this->addSql('DROP INDEX idx_3967a21650eae44 ON password_reset_tokens');
        $this->addSql('CREATE INDEX id_utilisateur ON password_reset_tokens (id_utilisateur)');
        $this->addSql('ALTER TABLE password_reset_tokens ADD CONSTRAINT FK_3967A21650EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE projets DROP FOREIGN KEY FK_B454C1DBD14DE5D1');
        $this->addSql('ALTER TABLE projets DROP FOREIGN KEY FK_B454C1DBD14DE5D1');
        $this->addSql('ALTER TABLE projets CHANGE description description TEXT DEFAULT NULL, CHANGE objectifs objectifs TEXT DEFAULT NULL, CHANGE etat etat ENUM(\'En attente\', \'Accepté\', \'Refusé\', \'En cours\', \'Terminé\') DEFAULT \'En attente\', CHANGE commentaire_admin commentaire_admin TEXT DEFAULT NULL, CHANGE date_soumission date_soumission DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE note_moyenne note_moyenne NUMERIC(3, 2) DEFAULT NULL, CHANGE evaluation_automatique evaluation_automatique TINYINT DEFAULT 0');
        $this->addSql('ALTER TABLE projets ADD CONSTRAINT `projets_ibfk_1` FOREIGN KEY (id_entrepreneur) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('DROP INDEX idx_b454c1dbd14de5d1 ON projets');
        $this->addSql('CREATE INDEX id_entrepreneur ON projets (id_entrepreneur)');
        $this->addSql('ALTER TABLE projets ADD CONSTRAINT FK_B454C1DBD14DE5D1 FOREIGN KEY (id_entrepreneur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reclamations DROP FOREIGN KEY FK_1CAD6B7650EAE44');
        $this->addSql('ALTER TABLE reclamations ADD adresse VARCHAR(500) DEFAULT NULL, ADD latitude NUMERIC(10, 8) DEFAULT NULL, ADD longitude NUMERIC(11, 8) DEFAULT NULL, ADD emotion VARCHAR(100) DEFAULT NULL, ADD reponse_admin TEXT DEFAULT NULL, ADD date_modification DATETIME DEFAULT NULL, CHANGE sujet sujet VARCHAR(150) DEFAULT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE statut statut VARCHAR(20) DEFAULT \'EN_ATTENTE\', CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE id_utilisateur id_utilisateur INT DEFAULT NULL');
        $this->addSql('DROP INDEX idx_1cad6b7650eae44 ON reclamations');
        $this->addSql('CREATE INDEX id_utilisateur ON reclamations (id_utilisateur)');
        $this->addSql('ALTER TABLE reclamations ADD CONSTRAINT FK_1CAD6B7650EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('ALTER TABLE reclamation_commentaires DROP FOREIGN KEY FK_5EAA37A6D672A9F3');
        $this->addSql('ALTER TABLE reclamation_commentaires DROP FOREIGN KEY FK_5EAA37A6236D04AD');
        $this->addSql('ALTER TABLE reclamation_commentaires CHANGE commentaire commentaire TEXT NOT NULL, CHANGE date_commentaire date_commentaire DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE id_reclamation id_reclamation INT NOT NULL, CHANGE id_auteur id_auteur INT DEFAULT 1 NOT NULL');
        $this->addSql('DROP INDEX idx_5eaa37a6d672a9f3 ON reclamation_commentaires');
        $this->addSql('CREATE INDEX id_reclamation ON reclamation_commentaires (id_reclamation)');
        $this->addSql('DROP INDEX idx_5eaa37a6236d04ad ON reclamation_commentaires');
        $this->addSql('CREATE INDEX fk_commentaire_auteur ON reclamation_commentaires (id_auteur)');
        $this->addSql('ALTER TABLE reclamation_commentaires ADD CONSTRAINT FK_5EAA37A6D672A9F3 FOREIGN KEY (id_reclamation) REFERENCES reclamations (id_reclamation) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reclamation_commentaires ADD CONSTRAINT FK_5EAA37A6236D04AD FOREIGN KEY (id_auteur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservations DROP FOREIGN KEY FK_4DA2398B13D439');
        $this->addSql('ALTER TABLE reservations DROP FOREIGN KEY FK_4DA23950EAE44');
        $this->addSql('ALTER TABLE reservations DROP FOREIGN KEY FK_4DA2398B13D439');
        $this->addSql('ALTER TABLE reservations DROP FOREIGN KEY FK_4DA23950EAE44');
        $this->addSql('ALTER TABLE reservations CHANGE date_reservation date_reservation DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT `reservations_ibfk_1` FOREIGN KEY (id_evenement) REFERENCES evenements (id_evenement)');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT `reservations_ibfk_2` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('DROP INDEX idx_4da2398b13d439 ON reservations');
        $this->addSql('CREATE INDEX id_evenement ON reservations (id_evenement)');
        $this->addSql('DROP INDEX idx_4da23950eae44 ON reservations');
        $this->addSql('CREATE INDEX id_utilisateur ON reservations (id_utilisateur)');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA2398B13D439 FOREIGN KEY (id_evenement) REFERENCES evenements (id_evenement) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA23950EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ressources DROP FOREIGN KEY FK_6A2CD5C72E8C07C5');
        $this->addSql('ALTER TABLE ressources DROP FOREIGN KEY FK_6A2CD5C72E8C07C5');
        $this->addSql('ALTER TABLE ressources DROP is_banned, DROP moderation_score, DROP moderation_reason, CHANGE nom nom VARCHAR(150) DEFAULT NULL, CHANGE offre offre VARCHAR(30) DEFAULT NULL, CHANGE type_r type_r VARCHAR(30) DEFAULT NULL, CHANGE image_r image_r VARCHAR(255) DEFAULT NULL, CHANGE prix_achat prix_achat FLOAT DEFAULT NULL, CHANGE disponibilite disponibilite TINYINT DEFAULT 1, CHANGE prix_louer prix_louer FLOAT DEFAULT NULL, CHANGE unite_louer unite_louer VARCHAR(30) DEFAULT NULL, CHANGE quantite quantite INT DEFAULT NULL, CHANGE etat etat VARCHAR(30) DEFAULT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE ressources ADD CONSTRAINT `ressources_ibfk_1` FOREIGN KEY (id_fournisseur) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('DROP INDEX idx_6a2cd5c72e8c07c5 ON ressources');
        $this->addSql('CREATE INDEX id_fournisseur ON ressources (id_fournisseur)');
        $this->addSql('ALTER TABLE ressources ADD CONSTRAINT FK_6A2CD5C72E8C07C5 FOREIGN KEY (id_fournisseur) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('DROP INDEX uniq_b63e2ec7a5b94004 ON roles');
        $this->addSql('CREATE UNIQUE INDEX nom_role ON roles (nom_role)');
        $this->addSql('ALTER TABLE sprints DROP FOREIGN KEY FK_4EE4697176222944');
        $this->addSql('ALTER TABLE sprints CHANGE objectif objectif TEXT DEFAULT NULL, CHANGE statut statut ENUM(\'À_venir\', \'Actif\', \'Terminé\', \'Annulé\') DEFAULT \'À_venir\', CHANGE capacite_equipe capacite_equipe INT DEFAULT 0, CHANGE velocite_prevue velocite_prevue INT DEFAULT 0, CHANGE velocite_reelle velocite_reelle INT DEFAULT 0, CHANGE id_projet id_projet INT NOT NULL');
        $this->addSql('DROP INDEX idx_4ee4697176222944 ON sprints');
        $this->addSql('CREATE INDEX id_projet ON sprints (id_projet)');
        $this->addSql('ALTER TABLE sprints ADD CONSTRAINT FK_4EE4697176222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE taches DROP FOREIGN KEY FK_3BF2CD9876222944');
        $this->addSql('ALTER TABLE taches DROP FOREIGN KEY FK_3BF2CD98C9B7E05A');
        $this->addSql('ALTER TABLE taches DROP FOREIGN KEY FK_3BF2CD984A40C0F0');
        $this->addSql('ALTER TABLE taches DROP FOREIGN KEY FK_3BF2CD9876222944');
        $this->addSql('ALTER TABLE taches DROP FOREIGN KEY FK_3BF2CD98C9B7E05A');
        $this->addSql('ALTER TABLE taches DROP FOREIGN KEY FK_3BF2CD984A40C0F0');
        $this->addSql('ALTER TABLE taches CHANGE description description TEXT DEFAULT NULL, CHANGE statut statut ENUM(\'À faire\', \'En cours\', \'Terminée\') DEFAULT \'À faire\'');
        $this->addSql('ALTER TABLE taches ADD CONSTRAINT `taches_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet)');
        $this->addSql('ALTER TABLE taches ADD CONSTRAINT `taches_ibfk_2` FOREIGN KEY (id_responsable) REFERENCES utilisateurs (id_utilisateur)');
        $this->addSql('ALTER TABLE taches ADD CONSTRAINT `taches_ibfk_3` FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE SET NULL');
        $this->addSql('DROP INDEX idx_3bf2cd9876222944 ON taches');
        $this->addSql('CREATE INDEX id_projet ON taches (id_projet)');
        $this->addSql('DROP INDEX idx_3bf2cd984a40c0f0 ON taches');
        $this->addSql('CREATE INDEX id_responsable ON taches (id_responsable)');
        $this->addSql('DROP INDEX idx_3bf2cd98c9b7e05a ON taches');
        $this->addSql('CREATE INDEX id_sprint ON taches (id_sprint)');
        $this->addSql('ALTER TABLE taches ADD CONSTRAINT FK_3BF2CD9876222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE taches ADD CONSTRAINT FK_3BF2CD98C9B7E05A FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE taches ADD CONSTRAINT FK_3BF2CD984A40C0F0 FOREIGN KEY (id_responsable) REFERENCES utilisateurs (id_utilisateur) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE userstory DROP FOREIGN KEY FK_CCF238EA76222944');
        $this->addSql('ALTER TABLE userstory DROP FOREIGN KEY FK_CCF238EAC9B7E05A');
        $this->addSql('ALTER TABLE userstory DROP FOREIGN KEY FK_CCF238EA76222944');
        $this->addSql('ALTER TABLE userstory DROP FOREIGN KEY FK_CCF238EAC9B7E05A');
        $this->addSql('ALTER TABLE userstory CHANGE id_userstory id_userstory INT AUTO_INCREMENT NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE story_points story_points INT DEFAULT NULL, CHANGE priorite priorite ENUM(\'Critique\', \'Haute\', \'Moyenne\', \'Basse\') DEFAULT \'Moyenne\', CHANGE statut statut ENUM(\'Backlog\', \'Prête\', \'En_cours\', \'Terminée\') DEFAULT \'Backlog\', CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE en_tant_que en_tant_que VARCHAR(255) DEFAULT NULL, CHANGE je_veux je_veux VARCHAR(255) DEFAULT NULL, CHANGE afin_de afin_de VARCHAR(255) DEFAULT NULL, CHANGE criteres_acceptation criteres_acceptation TEXT DEFAULT NULL, CHANGE id_projet id_projet INT NOT NULL');
        $this->addSql('ALTER TABLE userstory ADD CONSTRAINT `userstory_ibfk_1` FOREIGN KEY (id_projet) REFERENCES projets (id_projet)');
        $this->addSql('ALTER TABLE userstory ADD CONSTRAINT `userstory_ibfk_2` FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint)');
        $this->addSql('DROP INDEX idx_ccf238ea76222944 ON userstory');
        $this->addSql('CREATE INDEX id_projet ON userstory (id_projet)');
        $this->addSql('DROP INDEX idx_ccf238eac9b7e05a ON userstory');
        $this->addSql('CREATE INDEX id_sprint ON userstory (id_sprint)');
        $this->addSql('ALTER TABLE userstory ADD CONSTRAINT FK_CCF238EA76222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE userstory ADD CONSTRAINT FK_CCF238EAC9B7E05A FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_stories DROP FOREIGN KEY FK_C4868355C9B7E05A');
        $this->addSql('ALTER TABLE user_stories DROP FOREIGN KEY FK_C486835568FEC9');
        $this->addSql('ALTER TABLE user_stories DROP FOREIGN KEY FK_C486835576222944');
        $this->addSql('ALTER TABLE user_stories DROP FOREIGN KEY FK_C4868355C9B7E05A');
        $this->addSql('ALTER TABLE user_stories DROP FOREIGN KEY FK_C486835568FEC9');
        $this->addSql('ALTER TABLE user_stories CHANGE id_user_story id_user_story INT AUTO_INCREMENT NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE story_points story_points INT DEFAULT 1, CHANGE priorite priorite ENUM(\'Critique\', \'Haute\', \'Moyenne\', \'Basse\') DEFAULT \'Moyenne\', CHANGE statut statut ENUM(\'Backlog\', \'Prête\', \'En_cours\', \'Terminée\', \'Rejetée\') DEFAULT \'Backlog\', CHANGE date_completion date_completion DATE DEFAULT NULL, CHANGE criteres_acceptation criteres_acceptation TEXT DEFAULT NULL, CHANGE membre_nom membre_nom VARCHAR(100) DEFAULT NULL, CHANGE date_debut date_debut DATE DEFAULT NULL, CHANGE id_projet id_projet INT NOT NULL');
        $this->addSql('ALTER TABLE user_stories ADD CONSTRAINT `fk_user_stories_membre_equipe` FOREIGN KEY (id_membre_equipe) REFERENCES membres_equipe (id_membre) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_stories ADD CONSTRAINT `user_stories_ibfk_2` FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE SET NULL');
        $this->addSql('DROP INDEX idx_c486835576222944 ON user_stories');
        $this->addSql('CREATE INDEX id_projet ON user_stories (id_projet)');
        $this->addSql('DROP INDEX idx_c4868355c9b7e05a ON user_stories');
        $this->addSql('CREATE INDEX id_sprint ON user_stories (id_sprint)');
        $this->addSql('DROP INDEX idx_c486835568fec9 ON user_stories');
        $this->addSql('CREATE INDEX fk_user_stories_membre_equipe ON user_stories (id_membre_equipe)');
        $this->addSql('ALTER TABLE user_stories ADD CONSTRAINT FK_C486835576222944 FOREIGN KEY (id_projet) REFERENCES projets (id_projet) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_stories ADD CONSTRAINT FK_C4868355C9B7E05A FOREIGN KEY (id_sprint) REFERENCES sprints (id_sprint) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_stories ADD CONSTRAINT FK_C486835568FEC9 FOREIGN KEY (id_membre_equipe) REFERENCES membres_equipe (id_membre) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_story_assignments DROP FOREIGN KEY FK_38BD834968FEC9');
        $this->addSql('ALTER TABLE user_story_assignments CHANGE id_assignment id_assignment INT AUTO_INCREMENT NOT NULL, CHANGE id_user_story id_user_story INT NOT NULL, CHANGE id_membre_equipe id_membre_equipe INT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX unique_assignment ON user_story_assignments (id_user_story, id_membre_equipe)');
        $this->addSql('DROP INDEX idx_38bd834968fec9 ON user_story_assignments');
        $this->addSql('CREATE INDEX id_membre_equipe ON user_story_assignments (id_membre_equipe)');
        $this->addSql('ALTER TABLE user_story_assignments ADD CONSTRAINT FK_38BD834968FEC9 FOREIGN KEY (id_membre_equipe) REFERENCES membres_equipe (id_membre) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateurs DROP FOREIGN KEY FK_497B315EDC499668');
        $this->addSql('ALTER TABLE utilisateurs CHANGE nom nom VARCHAR(100) DEFAULT NULL, CHANGE date_inscription date_inscription DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE actif actif TINYINT DEFAULT 1, CHANGE bio bio TEXT DEFAULT NULL, CHANGE competences competences TEXT DEFAULT NULL, CHANGE badge_verifie badge_verifie TINYINT DEFAULT 0, CHANGE profil_complet profil_complet TINYINT DEFAULT 0, CHANGE adresse adresse VARCHAR(500) DEFAULT NULL, CHANGE latitude latitude NUMERIC(10, 8) DEFAULT NULL, CHANGE longitude longitude NUMERIC(11, 8) DEFAULT NULL, CHANGE badge_verification badge_verification TINYINT DEFAULT 0, CHANGE avatar_url avatar_url VARCHAR(500) DEFAULT NULL');
        $this->addSql('DROP INDEX idx_497b315edc499668 ON utilisateurs');
        $this->addSql('CREATE INDEX id_role ON utilisateurs (id_role)');
        $this->addSql('DROP INDEX uniq_497b315ee7927c74 ON utilisateurs');
        $this->addSql('CREATE UNIQUE INDEX email ON utilisateurs (email)');
        $this->addSql('ALTER TABLE utilisateurs ADD CONSTRAINT FK_497B315EDC499668 FOREIGN KEY (id_role) REFERENCES roles (id_role)');
    }
}
